[database]
addrs= "localhost:27018"
user= "iris"
passwd= "irispassword"
database= "rainbow-server-check"

[server]
bech_32_chain_prefix="i"
write_dir="/Users/user/adr038-iris"
file_prefix="adr38"
chain_id=""
promethous_port=9091
only_support_module=""